# Konfigurasi Railway agar pakai PHP 8.4 & Ekstensi Lengkap

[phases.setup]
nixPkgs = [
    "php84",
    "php84Extensions.intl",
    "php84Extensions.gd",
    "php84Extensions.zip",
    "php84Extensions.pdo",
    "php84Extensions.mysql",
    "php84Extensions.bcmath",
    "php84Extensions.fileinfo",
    "php84Extensions.xml",
    "php84Extensions.mbstring",
    "php84Extensions.curl",
    "php84Extensions.tokenizer",
    "php84Extensions.openssl",
    "composer",
    "git",
    "unzip"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev --ignore-platform-reqs",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"